"""Migrations are the source of truth for the schema (T-006; specification §23).

These tests exist to catch the two failures that silently corrupt a schema over time: a
migration that cannot be reversed, and a model that has drifted from the migrations that are
supposed to define it.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import Engine

from app.db.base import NAMING_CONVENTION, Base
from tests.conftest import BACKEND, alembic_config, render_url


def test_upgrade_head_then_downgrade_base(database_url: str) -> None:
    """A migration that cannot be undone is a migration that cannot be deployed safely."""
    config = alembic_config(database_url)
    engine = create_engine(database_url, connect_args={"connect_timeout": 5})

    try:
        command.upgrade(config, "head")
        assert _current_revision(engine) is not None, "upgrade left no version stamp"

        command.downgrade(config, "base")
        assert _current_revision(engine) is None, "downgrade did not unwind to base"

        command.upgrade(config, "head")
        assert _current_revision(engine) is not None, "re-upgrade after downgrade failed"
    finally:
        engine.dispose()


def test_alembic_check_reports_no_pending_model_changes(migrated_engine: Engine) -> None:
    """`alembic check` fails if a model exists that no migration creates, or vice versa."""
    config = alembic_config(render_url(migrated_engine.url))

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on real drift
        pytest.fail(f"models and migrations disagree; generate a revision: {exc}")


def test_every_revision_is_reachable_from_a_single_head() -> None:
    """Multiple heads mean an ambiguous upgrade path and a merge nobody noticed was needed."""
    heads = ScriptDirectory(str(BACKEND / "alembic")).get_heads()

    assert len(heads) == 1, f"expected exactly one migration head, found {heads}"


def test_migration_files_are_present() -> None:
    versions = list((BACKEND / "alembic" / "versions").glob("*.py"))

    assert versions, "no migration files found"


def test_naming_convention_is_bound_to_the_metadata() -> None:
    """Without deterministic names, autogenerate diffs are unstable and downgrades unreliable."""
    assert Base.metadata.naming_convention == NAMING_CONVENTION
    assert set(NAMING_CONVENTION) == {"ix", "uq", "ck", "fk", "pk"}


def test_migrations_stamp_the_database_and_build_the_schema(migrated_engine: Engine) -> None:
    """Migrations, and only migrations, produce the schema.

    ``alembic check`` above is the authority on models agreeing with migrations; this asserts
    the upgrade actually ran and left its bookkeeping behind.
    """
    tables = set(inspect(migrated_engine).get_table_names())

    assert "alembic_version" in tables, "alembic did not stamp the database"
    assert "audit_event" in tables, "T-011's table is missing from the migrated schema"


def test_the_audit_trail_keeps_its_append_only_guards(migrated_engine: Engine) -> None:
    """Migrations own the triggers too — a schema rebuilt without them is not append-only."""
    with migrated_engine.connect() as connection:
        triggers = {
            row[0]
            for row in connection.execute(
                text(
                    "SELECT tgname FROM pg_trigger "
                    "WHERE tgrelid = 'audit_event'::regclass AND NOT tgisinternal"
                )
            )
        }

    assert triggers == {"audit_event_no_update_or_delete", "audit_event_no_truncate"}


def test_env_py_documents_where_models_must_be_registered() -> None:
    """A model nobody imports is invisible to `alembic check`; the instruction must not be lost."""
    env = (BACKEND / "alembic" / "env.py").read_text(encoding="utf-8")

    assert "_load_all_models" in env
    assert "alembic check" in env


def _current_revision(engine: Engine) -> str | None:
    with engine.connect() as connection:
        if not inspect(engine).has_table("alembic_version"):
            return None
        return connection.execute(
            text("SELECT version_num FROM alembic_version")
        ).scalar_one_or_none()


def test_nothing_builds_the_schema_with_create_all() -> None:
    """`create_all` would let models and migrations diverge without any test noticing."""
    # Match the call form, not the prose mentions in docstrings explaining why it is banned.
    # This file is excluded because it necessarily contains the pattern it searches for.
    offenders = [
        path.relative_to(BACKEND)
        for path in (*(BACKEND / "app").rglob("*.py"), *(BACKEND / "tests").rglob("*.py"))
        if path.name != Path(__file__).name and ".create_all(" in path.read_text(encoding="utf-8")
    ]

    assert not offenders, f"schema must come from migrations only; found create_all in {offenders}"


def test_alembic_ini_commits_no_connection_string() -> None:
    """A URL in alembic.ini would be a credential in git (AGENTS.md rule 3)."""
    ini = Path(BACKEND / "alembic.ini").read_text(encoding="utf-8")
    url_line = next(line for line in ini.splitlines() if line.startswith("sqlalchemy.url"))

    assert url_line.split("=", 1)[1].strip() == "", "alembic.ini must not carry a database URL"
