"""approval

Revision ID: 0133f6adb316
Revises: 57804e6a27d7
Created: 2026-07-29 10:28:37.161082
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0133f6adb316"
down_revision: str | None = "57804e6a27d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_revision_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_contact_point_id", sa.Uuid(), nullable=False),
        sa.Column("approver_id", sa.String(length=255), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "EXPIRED", "REVOKED", name="approvalstate"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_reason", sa.Text(), nullable=True),
        sa.Column("approved_content_hash", sa.String(length=64), nullable=False),
        sa.Column("product_status_version_id", sa.Uuid(), nullable=True),
        sa.Column("approved_claim_set_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state IN ('REJECTED', 'EXPIRED', 'REVOKED')) = (closed_at IS NOT NULL)",
            name=op.f("ck_approval_closed_state_needs_a_timestamp"),
        ),
        sa.CheckConstraint(
            "approved_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_approval_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "approval_expires_at > created_at", name=op.f("ck_approval_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "length(trim(approver_id)) > 0", name=op.f("ck_approval_approver_id_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["approved_claim_set_id"],
            ["approved_claim_set.id"],
            name=op.f("fk_approval_approved_claim_set_id_approved_claim_set"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_revision_id"],
            ["message_revision.id"],
            name=op.f("fk_approval_message_revision_id_message_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_status_version_id"],
            ["product_status_version.id"],
            name=op.f("fk_approval_product_status_version_id_product_status_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_contact_point_id"],
            ["contact_point.id"],
            name=op.f("fk_approval_recipient_contact_point_id_contact_point"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.create_index("ix_approval_state", "approval", ["state"], unique=False)
    op.create_index(
        "uq_approval_live_per_revision",
        "approval",
        ["message_revision_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('PENDING', 'APPROVED')"),
    )
    # ### end Alembic commands ###

    # What was approved cannot be re-pinned (§8.4, §11.4).
    #
    # The approval names one revision, one recipient, one content hash, one product status
    # version, and one claim set. If any of those could be edited, an operator could quietly
    # re-point an existing approval at different content or a newer claim set — which is exactly
    # the re-approval that §8.4 requires. State and closure fields stay mutable so the approval
    # can progress and be revoked.
    op.execute(
        """
        CREATE FUNCTION approval_pins_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.message_revision_id IS DISTINCT FROM OLD.message_revision_id
               OR NEW.recipient_contact_point_id IS DISTINCT FROM OLD.recipient_contact_point_id
               OR NEW.approver_id IS DISTINCT FROM OLD.approver_id
               OR NEW.approved_content_hash IS DISTINCT FROM OLD.approved_content_hash
               OR NEW.product_status_version_id IS DISTINCT FROM OLD.product_status_version_id
               OR NEW.approved_claim_set_id IS DISTINCT FROM OLD.approved_claim_set_id
               OR NEW.approval_expires_at IS DISTINCT FROM OLD.approval_expires_at
            THEN
                RAISE EXCEPTION
                    'approval scope is immutable; request a new approval instead '
                    '(specification 8.4, 11.4)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER approval_no_repin
        BEFORE UPDATE ON approval
        FOR EACH ROW EXECUTE FUNCTION approval_pins_immutable();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS approval_no_repin ON approval")
    op.execute("DROP FUNCTION IF EXISTS approval_pins_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_approval_live_per_revision",
        table_name="approval",
        postgresql_where=sa.text("state IN ('PENDING', 'APPROVED')"),
    )
    op.drop_index("ix_approval_state", table_name="approval")
    op.drop_table("approval")
    # ### end Alembic commands ###

    sa.Enum(name="approvalstate").drop(op.get_bind(), checkfirst=True)
