"""approved claims and claim sets

Revision ID: 173f99bbd4a0
Revises: 5a91cde91f87
Created: 2026-07-29 06:51:42.817543
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "173f99bbd4a0"
down_revision: str | None = "5a91cde91f87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approved_claim",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("allow_paraphrase", sa.Boolean(), nullable=False),
        sa.Column("paraphrase_constraints", sa.Text(), nullable=True),
        # `readinesscategory` was created by revision 259218227532. Autogenerate does not know the
        # type already exists and emits a second CREATE TYPE, which fails; `create_type=False`
        # reuses it. Any future migration referencing an existing enum needs the same treatment.
        sa.Column(
            "presumes_readiness",
            postgresql.ENUM(name="readinesscategory", create_type=False),
            nullable=True,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_date", sa.Date(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_or_review_by", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_claim_id", sa.Uuid(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allow_paraphrase = false OR paraphrase_constraints IS NOT NULL",
            name=op.f("ck_approved_claim_paraphrase_requires_constraints"),
        ),
        sa.CheckConstraint(
            "expires_or_review_by > effective_from",
            name=op.f("ck_approved_claim_review_date_after_effective_from"),
        ),
        sa.CheckConstraint(
            "length(trim(approved_by)) > 0", name=op.f("ck_approved_claim_approved_by_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(claim_key)) > 0", name=op.f("ck_approved_claim_claim_key_not_blank")
        ),
        sa.CheckConstraint("length(trim(text)) > 0", name=op.f("ck_approved_claim_text_not_blank")),
        sa.CheckConstraint("version > 0", name=op.f("ck_approved_claim_version_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_approved_claim_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
            name=op.f("fk_approved_claim_source_document_id_source_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_claim_id"],
            ["approved_claim.id"],
            name=op.f("fk_approved_claim_supersedes_claim_id_approved_claim"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_claim")),
        sa.UniqueConstraint("claim_key", "version", name="uq_approved_claim_key_version"),
    )
    op.create_index(
        "ix_approved_claim_effective_from", "approved_claim", ["effective_from"], unique=False
    )
    op.create_index("ix_approved_claim_product_id", "approved_claim", ["product_id"], unique=False)
    op.create_table(
        "approved_claim_campaign",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_approved_claim_campaign_campaign_id_campaign"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["approved_claim.id"],
            name=op.f("fk_approved_claim_campaign_claim_id_approved_claim"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_claim_campaign")),
        sa.UniqueConstraint("claim_id", "campaign_id", name="uq_approved_claim_campaign"),
    )
    op.create_index(
        "ix_approved_claim_campaign_campaign_id",
        "approved_claim_campaign",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "approved_claim_set",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(approved_by)) > 0",
            name=op.f("ck_approved_claim_set_approved_by_not_blank"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_approved_claim_set_version_positive")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_approved_claim_set_campaign_id_campaign"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_approved_claim_set_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_claim_set")),
        sa.UniqueConstraint(
            "product_id", "campaign_id", "version", name="uq_approved_claim_set_scope_version"
        ),
    )
    op.create_index(
        "ix_approved_claim_set_scope",
        "approved_claim_set",
        ["product_id", "campaign_id"],
        unique=False,
    )
    op.create_table(
        "approved_claim_set_member",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_set_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["approved_claim.id"],
            name=op.f("fk_approved_claim_set_member_claim_id_approved_claim"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["claim_set_id"],
            ["approved_claim_set.id"],
            name=op.f("fk_approved_claim_set_member_claim_set_id_approved_claim_set"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_claim_set_member")),
        sa.UniqueConstraint("claim_set_id", "claim_id", name="uq_approved_claim_set_member"),
    )
    op.create_index(
        "ix_approved_claim_set_member_claim_id",
        "approved_claim_set_member",
        ["claim_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # An approved claim's wording and approval are immutable (§10.5, §15.7).
    #
    # "An approved claim stores exact wording": if that text could be edited in place, a message
    # already approved against claim v1 would silently start saying something nobody approved.
    # Editing means publishing v2 and superseding v1.
    #
    # `superseded_at` stays mutable — retiring a claim is how a successor takes over.
    op.execute(
        """
        CREATE FUNCTION approved_claim_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.claim_key IS DISTINCT FROM OLD.claim_key
               OR NEW.version IS DISTINCT FROM OLD.version
               OR NEW.product_id IS DISTINCT FROM OLD.product_id
               OR NEW.text IS DISTINCT FROM OLD.text
               OR NEW.allow_paraphrase IS DISTINCT FROM OLD.allow_paraphrase
               OR NEW.paraphrase_constraints IS DISTINCT FROM OLD.paraphrase_constraints
               OR NEW.approved_by IS DISTINCT FROM OLD.approved_by
               OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
               OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
               OR NEW.expires_or_review_by IS DISTINCT FROM OLD.expires_or_review_by
               OR NEW.is_synthetic IS DISTINCT FROM OLD.is_synthetic
            THEN
                RAISE EXCEPTION
                    'approved_claim is immutable once written; publish a new version and '
                    'supersede this one (specification 10.5)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER approved_claim_no_rewrite
        BEFORE UPDATE ON approved_claim
        FOR EACH ROW EXECUTE FUNCTION approved_claim_immutable();
        """
    )

    # A published set's membership cannot be *repointed* at a different claim; publish a new set
    # version instead (§11.4).
    #
    # UPDATE only, deliberately. DELETE is left alone because removing a claim set (or the
    # campaign above it) legitimately cascades to its members, and a BEFORE DELETE trigger
    # cannot distinguish a cascade from a direct delete. Swapping a member's claim silently
    # changes what an approved set says; deleting a whole set is a visible administrative act.
    op.execute(
        """
        CREATE FUNCTION approved_claim_set_member_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'approved_claim_set_member is fixed once written; publish a new claim set '
                'version instead (specification 11.4)'
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER approved_claim_set_member_no_change
        BEFORE UPDATE ON approved_claim_set_member
        FOR EACH ROW EXECUTE FUNCTION approved_claim_set_member_immutable();
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS approved_claim_set_member_no_change ON approved_claim_set_member"
    )
    op.execute("DROP FUNCTION IF EXISTS approved_claim_set_member_immutable()")
    op.execute("DROP TRIGGER IF EXISTS approved_claim_no_rewrite ON approved_claim")
    op.execute("DROP FUNCTION IF EXISTS approved_claim_immutable()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approved_claim_set_member_claim_id", table_name="approved_claim_set_member")
    op.drop_table("approved_claim_set_member")
    op.drop_index("ix_approved_claim_set_scope", table_name="approved_claim_set")
    op.drop_table("approved_claim_set")
    op.drop_index("ix_approved_claim_campaign_campaign_id", table_name="approved_claim_campaign")
    op.drop_table("approved_claim_campaign")
    op.drop_index("ix_approved_claim_product_id", table_name="approved_claim")
    op.drop_index("ix_approved_claim_effective_from", table_name="approved_claim")
    op.drop_table("approved_claim")
    # ### end Alembic commands ###
