"""webhook event intake

Revision ID: 224564968fc6
Revises: 025c23d5d4bc
Created: 2026-07-29 20:44:14.401023
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "224564968fc6"
down_revision: str | None = "025c23d5d4bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("RECEIVED", "ENQUEUED", "PROCESSED", "FAILED", name="webhookprocessingstate"),
            nullable=False,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(external_event_id)) > 0",
            name=op.f("ck_webhook_event_webhook_external_event_id_not_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(provider)) > 0", name=op.f("ck_webhook_event_webhook_provider_not_blank")
        ),
        sa.CheckConstraint(
            "signature_valid", name=op.f("ck_webhook_event_webhook_event_must_be_verified")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_event")),
        sa.UniqueConstraint(
            "provider", "external_event_id", name="uq_webhook_event_provider_external_id"
        ),
    )
    op.create_index("ix_webhook_event_received_at", "webhook_event", ["received_at"], unique=False)
    op.create_index(
        "ix_webhook_event_unprocessed",
        "webhook_event",
        ["received_at"],
        unique=False,
        postgresql_where=sa.text("state IN ('RECEIVED', 'ENQUEUED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_webhook_event_unprocessed",
        table_name="webhook_event",
        postgresql_where=sa.text("state IN ('RECEIVED', 'ENQUEUED')"),
    )
    op.drop_index("ix_webhook_event_received_at", table_name="webhook_event")
    op.drop_table("webhook_event")
    # `drop_table` leaves the enum type behind, so a later re-upgrade fails with
    # "type webhookprocessingstate already exists". See docs/development.md.
    sa.Enum(name="webhookprocessingstate").drop(op.get_bind(), checkfirst=True)
