"""product, status version, source document

Revision ID: 259218227532
Revises: 6ea1f40a0e13
Created: 2026-07-29 05:42:40.193476
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "259218227532"
down_revision: str | None = "6ea1f40a0e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `btree_gist` lets an exclusion constraint mix equality (product_id) with range overlap.
    # Contrib extension, present in the postgres:16 image.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_product_name_not_blank")),
        sa.CheckConstraint("length(trim(slug)) > 0", name=op.f("ck_product_slug_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("slug", name="uq_product_slug"),
    )
    op.create_table(
        "source_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("source_date", sa.Date(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_source_document_title_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document")),
    )
    op.create_index(
        "ix_source_document_source_date", "source_document", ["source_date"], unique=False
    )
    op.create_table(
        "product_status_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "readiness_category",
            sa.Enum(
                "SELLABLE_NOW",
                "EVALUATION_OR_PILOT",
                "IN_DEVELOPMENT",
                "STRATEGIC_OR_ROADMAP",
                "PAUSED_OR_UNAVAILABLE",
                name="readinesscategory",
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_date", sa.Date(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_or_review_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_or_review_by IS NULL OR expires_or_review_by > effective_from",
            name=op.f("ck_product_status_version_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "length(trim(approved_by)) > 0",
            name=op.f("ck_product_status_version_approved_by_not_blank"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_product_status_version_version_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_status_version_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
            name=op.f("fk_product_status_version_source_document_id_source_document"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["product_status_version.id"],
            name=op.f("fk_product_status_version_supersedes_version_id_product_status_version"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_status_version")),
        sa.UniqueConstraint(
            "product_id", "version", name="uq_product_status_version_product_version"
        ),
    )
    op.create_index(
        "ix_product_status_version_effective_from",
        "product_status_version",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        "ix_product_status_version_product_id",
        "product_status_version",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Exactly one readiness answer per product per instant (§2.3, GP-12).
    #
    # Enforced by the database, not by a read-then-write check: two concurrent writers would
    # both pass an application-level check and commit overlapping windows, leaving the product
    # with two "current" readiness answers and no way to tell which one a draft relied on.
    #
    # `[)` bounds: a window ending exactly when the next begins is a clean handover, not an
    # overlap. A NULL upper bound is unbounded — it runs until something supersedes it.
    op.execute(
        """
        ALTER TABLE product_status_version
        ADD CONSTRAINT ex_product_status_version_no_overlap
        EXCLUDE USING gist (
            product_id WITH =,
            tstzrange(effective_from, expires_or_review_by, '[)') WITH &&
        )
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE product_status_version "
        "DROP CONSTRAINT IF EXISTS ex_product_status_version_no_overlap"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_status_version_product_id", table_name="product_status_version")
    op.drop_index("ix_product_status_version_effective_from", table_name="product_status_version")
    op.drop_table("product_status_version")
    op.drop_index("ix_source_document_source_date", table_name="source_document")
    op.drop_table("source_document")
    op.drop_table("product")
    # ### end Alembic commands ###

    # Enum types outlive their tables; a re-upgrade fails without this.
    sa.Enum(name="readinesscategory").drop(op.get_bind(), checkfirst=True)

    # btree_gist is left installed: other tables may come to depend on it, and dropping a
    # shared extension during one table's downgrade would be a surprising side effect.
