"""audit event uses clock_timestamp for orderable history

Revision ID: 262585e960c1
Revises: 0133f6adb316
Created: 2026-07-29 10:31:24.382536
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "262585e960c1"
down_revision: str | None = "0133f6adb316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_event",
        "occurred_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("clock_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_event",
        "occurred_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
