"""operational flags

Revision ID: 4a4c4bf4623e
Revises: f09d40b96a8b
Created: 2026-07-29 15:41:31.844122
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4a4c4bf4623e"
down_revision: str | None = "f09d40b96a8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operational_flag",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "key",
            sa.Enum(
                "GLOBAL_PAUSE",
                "SHADOW_MODE",
                "OUTBOUND_EMAIL_DISABLED",
                "PRODUCT_DISABLED",
                "CLAIM_VERSION_DISABLED",
                name="flagkey",
            ),
            nullable=False,
        ),
        sa.Column("scope_id", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("set_by", sa.String(length=255), nullable=False),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(key IN ('PRODUCT_DISABLED', 'CLAIM_VERSION_DISABLED')) = (scope_id IS NOT NULL)",
            name=op.f("ck_operational_flag_scoped_keys_need_a_scope"),
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0", name=op.f("ck_operational_flag_flag_reason_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operational_flag")),
        sa.UniqueConstraint(
            "key",
            "scope_id",
            name="uq_operational_flag_key_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("operational_flag")
    # `drop_table` leaves the enum type behind, so a later re-upgrade fails with
    # "type flagkey already exists". See docs/development.md.
    sa.Enum(name="flagkey").drop(op.get_bind(), checkfirst=True)
