"""outreach thread send command attempts events

Revision ID: 4ad849bbfecc
Revises: 262585e960c1
Created: 2026-07-29 11:05:33.496954
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "4ad849bbfecc"
down_revision: str | None = "262585e960c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outreach_thread",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "NOT_STARTED",
                "QUEUED",
                "SENDING",
                "PROVIDER_ACCEPTED",
                "DELIVERY_UNKNOWN",
                "DELIVERED",
                "BOUNCED",
                "REPLIED",
                "UNSUBSCRIBED",
                "FAILED",
                name="outreachthreadstate",
            ),
            nullable=False,
        ),
        sa.Column("unresolved_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["campaign_candidate.id"],
            name=op.f("fk_outreach_thread_candidate_id_campaign_candidate"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_thread")),
        sa.UniqueConstraint("candidate_id", name="uq_outreach_thread_candidate"),
    )
    op.create_index("ix_outreach_thread_state", "outreach_thread", ["state"], unique=False)
    op.create_table(
        "interaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction", sa.Enum("OUTBOUND", "INBOUND", name="interactiondirection"), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("requires_human", sa.Boolean(), nullable=False),
        sa.Column("handled_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["outreach_thread.id"],
            name=op.f("fk_interaction_thread_id_outreach_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction")),
    )
    op.create_index("ix_interaction_thread_id", "interaction", ["thread_id"], unique=False)
    op.create_table(
        "send_command",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.Enum("EMAIL_SEND", name="actiontype"), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_contact_point_id", sa.Uuid(), nullable=False),
        sa.Column("message_revision_id", sa.Uuid(), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=False),
        sa.Column("approval_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "record_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("product_status_version_id", sa.Uuid(), nullable=True),
        sa.Column("approved_claim_set_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "idempotency_key ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_send_command_idempotency_key_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "length(trim(actor_id)) > 0", name=op.f("ck_send_command_actor_id_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval.id"],
            name=op.f("fk_send_command_approval_id_approval"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_claim_set_id"],
            ["approved_claim_set.id"],
            name=op.f("fk_send_command_approved_claim_set_id_approved_claim_set"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_send_command_campaign_id_campaign"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_revision_id"],
            ["message_revision.id"],
            name=op.f("fk_send_command_message_revision_id_message_revision"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_status_version_id"],
            ["product_status_version.id"],
            name=op.f("fk_send_command_product_status_version_id_product_status_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_contact_point_id"],
            ["contact_point.id"],
            name=op.f("fk_send_command_recipient_contact_point_id_contact_point"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["outreach_thread.id"],
            name=op.f("fk_send_command_thread_id_outreach_thread"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_send_command")),
        sa.UniqueConstraint("approval_id", name="uq_send_command_approval"),
        sa.UniqueConstraint("idempotency_key", name="uq_send_command_idempotency_key"),
    )
    op.create_index("ix_send_command_thread_id", "send_command", ["thread_id"], unique=False)
    op.create_table(
        "delivery_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("send_command_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "DELIVERED",
                "BOUNCED",
                "REPLIED",
                "UNSUBSCRIBED",
                "COMPLAINED",
                "DEFERRED",
                name="deliveryeventtype",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["send_command_id"],
            ["send_command.id"],
            name=op.f("fk_delivery_event_send_command_id_send_command"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["outreach_thread.id"],
            name=op.f("fk_delivery_event_thread_id_outreach_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_event")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_delivery_event_provider_event"
        ),
    )
    op.create_index(
        "ix_delivery_event_occurred_at", "delivery_event", ["occurred_at"], unique=False
    )
    op.create_index("ix_delivery_event_thread_id", "delivery_event", ["thread_id"], unique=False)
    op.create_table(
        "send_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("send_command_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "ACCEPTED",
                "AMBIGUOUS",
                "REJECTED",
                "RATE_LIMITED",
                "TIMEOUT",
                "REFUSED_BY_SHADOW_MODE",
                name="attemptoutcome",
            ),
            nullable=True,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("provider_response_code", sa.String(length=50), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_send_attempt_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["send_command_id"],
            ["send_command.id"],
            name=op.f("fk_send_attempt_send_command_id_send_command"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_send_attempt")),
        sa.UniqueConstraint(
            "send_command_id", "attempt_number", name="uq_send_attempt_command_number"
        ),
    )
    op.create_index("ix_send_attempt_command_id", "send_attempt", ["send_command_id"], unique=False)
    # ### end Alembic commands ###

    # A send command is an order, not a record that evolves (§11.4, ADR-016).
    #
    # Everything it carries is the evidence that this exact message, to this exact recipient, was
    # authorized by this exact approval under these product and claim versions. If any of it could
    # be edited, the idempotency key could be re-pointed at different content and the duplicate-
    # send guard would stop guarding anything.
    #
    # UPDATE is blocked outright: unlike a revision or an approval, a command has no state to
    # progress. What happened to it lives in send_attempt rows.
    op.execute(
        """
        CREATE FUNCTION send_command_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'send_command is immutable; record what happened in send_attempt instead '
                '(specification 11.4, ADR-016)'
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER send_command_no_rewrite
        BEFORE UPDATE ON send_command
        FOR EACH ROW EXECUTE FUNCTION send_command_immutable();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS send_command_no_rewrite ON send_command")
    op.execute("DROP FUNCTION IF EXISTS send_command_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_send_attempt_command_id", table_name="send_attempt")
    op.drop_table("send_attempt")
    op.drop_index("ix_delivery_event_thread_id", table_name="delivery_event")
    op.drop_index("ix_delivery_event_occurred_at", table_name="delivery_event")
    op.drop_table("delivery_event")
    op.drop_index("ix_send_command_thread_id", table_name="send_command")
    op.drop_table("send_command")
    op.drop_index("ix_interaction_thread_id", table_name="interaction")
    op.drop_table("interaction")
    op.drop_index("ix_outreach_thread_state", table_name="outreach_thread")
    op.drop_table("outreach_thread")
    # ### end Alembic commands ###

    for enum_name in (
        "outreachthreadstate",
        "actiontype",
        "attemptoutcome",
        "deliveryeventtype",
        "interactiondirection",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
