"""user session

Revision ID: 55202db10b03
Revises: ba1a2b2420a4
Created: 2026-07-31 05:00:31.733948
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "55202db10b03"
down_revision: str | None = "ba1a2b2420a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=255), nullable=True),
        sa.Column("issued_via", sa.String(length=50), nullable=False),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_by IS NULL)",
            name=op.f("ck_user_session_ck_user_session_revocation_is_attributed"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at",
            name=op.f("ck_user_session_ck_user_session_expiry_after_issue"),
        ),
        sa.CheckConstraint(
            "length(token_hash) = 64",
            name=op.f("ck_user_session_ck_user_session_token_hash_is_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_user_session_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_session_token_hash")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_session")
    # ### end Alembic commands ###
