"""message draft and revision

Revision ID: 57804e6a27d7
Revises: 6ed335d539bf
Created: 2026-07-29 09:53:06.376387
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "57804e6a27d7"
down_revision: str | None = "6ed335d539bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_draft",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose", sa.Enum("INITIAL_OUTREACH", "FOLLOW_UP", name="draftpurpose"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["campaign_candidate.id"],
            name=op.f("fk_message_draft_candidate_id_campaign_candidate"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_draft")),
    )
    op.create_index(
        "ix_message_draft_candidate_id", "message_draft", ["candidate_id"], unique=False
    )
    op.create_table(
        "message_revision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("recipient_contact_point_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("approved_claim_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "VALIDATION_FAILED",
                "REVIEW_PENDING",
                "APPROVED",
                "SUPERSEDED",
                "INVALIDATED",
                name="messagerevisionstate",
            ),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state IN ('SUPERSEDED', 'INVALIDATED')) = (retired_at IS NOT NULL)",
            name=op.f("ck_message_revision_retired_state_needs_a_timestamp"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_message_revision_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "length(trim(body)) > 0", name=op.f("ck_message_revision_body_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(created_by)) > 0", name=op.f("ck_message_revision_created_by_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(subject)) > 0", name=op.f("ck_message_revision_subject_not_blank")
        ),
        sa.CheckConstraint(
            "revision_number > 0", name=op.f("ck_message_revision_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["message_draft.id"],
            name=op.f("fk_message_revision_draft_id_message_draft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_contact_point_id"],
            ["contact_point.id"],
            name=op.f("fk_message_revision_recipient_contact_point_id_contact_point"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_revision")),
        sa.UniqueConstraint("draft_id", "revision_number", name="uq_message_revision_number"),
    )
    op.create_index("ix_message_revision_draft_id", "message_revision", ["draft_id"], unique=False)
    op.create_index("ix_message_revision_state", "message_revision", ["state"], unique=False)
    # ### end Alembic commands ###

    # A revision means the same thing forever (§10.5, §11.4).
    #
    # An approval binds to one exact message_revision_id, and the final send transaction rechecks
    # that revision. If the recipient, subject, body, or citations could be edited in place, an
    # approval would end up pointing at content nobody approved. Editing means creating revision
    # N+1 and superseding N.
    #
    # `state` and `retired_at` stay mutable: moving draft -> review_pending -> approved ->
    # superseded is how a revision progresses, and none of it changes what the message says.
    op.execute(
        """
        CREATE FUNCTION message_revision_content_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.draft_id IS DISTINCT FROM OLD.draft_id
               OR NEW.revision_number IS DISTINCT FROM OLD.revision_number
               OR NEW.recipient_contact_point_id IS DISTINCT FROM OLD.recipient_contact_point_id
               OR NEW.subject IS DISTINCT FROM OLD.subject
               OR NEW.body IS DISTINCT FROM OLD.body
               OR NEW.approved_claim_ids IS DISTINCT FROM OLD.approved_claim_ids
               OR NEW.evidence_ids IS DISTINCT FROM OLD.evidence_ids
               OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
               OR NEW.created_by IS DISTINCT FROM OLD.created_by
            THEN
                RAISE EXCEPTION
                    'message_revision content is immutable; editing creates a new revision and '
                    'supersedes this one (specification 10.5)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER message_revision_no_content_rewrite
        BEFORE UPDATE ON message_revision
        FOR EACH ROW EXECUTE FUNCTION message_revision_content_immutable();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS message_revision_no_content_rewrite ON message_revision")
    op.execute("DROP FUNCTION IF EXISTS message_revision_content_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_message_revision_state", table_name="message_revision")
    op.drop_index("ix_message_revision_draft_id", table_name="message_revision")
    op.drop_table("message_revision")
    op.drop_index("ix_message_draft_candidate_id", table_name="message_draft")
    op.drop_table("message_draft")
    # ### end Alembic commands ###

    for enum_name in ("draftpurpose", "messagerevisionstate"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
