"""campaign, target segment, policy version

Revision ID: 5a91cde91f87
Revises: 259218227532
Created: 2026-07-29 06:16:47.159202
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "5a91cde91f87"
down_revision: str | None = "259218227532"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_campaign_name_not_blank")),
        sa.CheckConstraint("length(trim(slug)) > 0", name=op.f("ck_campaign_slug_not_blank")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_campaign_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign")),
        sa.UniqueConstraint("slug", name="uq_campaign_slug"),
    )
    op.create_table(
        "campaign_policy_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(approved_by)) > 0",
            name=op.f("ck_campaign_policy_version_approved_by_not_blank"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_campaign_policy_version_version_positive")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_campaign_policy_version_campaign_id_campaign"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_policy_version")),
        sa.UniqueConstraint(
            "campaign_id", "version", name="uq_campaign_policy_version_campaign_ver"
        ),
    )
    op.create_index(
        "ix_campaign_policy_version_campaign_id",
        "campaign_policy_version",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "target_segment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(key)) > 0", name=op.f("ck_target_segment_key_not_blank")),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_target_segment_campaign_id_campaign"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_segment")),
        sa.UniqueConstraint("campaign_id", "key", name="uq_target_segment_campaign_key"),
    )
    op.create_index(
        "ix_target_segment_campaign_id", "target_segment", ["campaign_id"], unique=False
    )
    # ### end Alembic commands ###

    # A policy version is immutable in everything that defines it (GP-09, §17.5).
    #
    # Qualification runs, drafts, and approvals record which policy version judged them.
    # Rewriting the rules afterwards would make those recorded decisions unexplainable — the
    # audit trail would say "approved under v2" while v2 said something else entirely.
    #
    # `superseded_at` is the one mutable column: retiring a version is how a *new* version takes
    # over, and it does not change what the old rules said.
    op.execute(
        """
        CREATE FUNCTION campaign_policy_version_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.campaign_id IS DISTINCT FROM OLD.campaign_id
               OR NEW.version IS DISTINCT FROM OLD.version
               OR NEW.policy IS DISTINCT FROM OLD.policy
               OR NEW.approved_by IS DISTINCT FROM OLD.approved_by
               OR NEW.approved_at IS DISTINCT FROM OLD.approved_at
            THEN
                RAISE EXCEPTION
                    'campaign_policy_version is immutable once written; publish a new version '
                    'instead (specification GP-09)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER campaign_policy_version_no_rewrite
        BEFORE UPDATE ON campaign_policy_version
        FOR EACH ROW EXECUTE FUNCTION campaign_policy_version_immutable();
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS campaign_policy_version_no_rewrite ON campaign_policy_version"
    )
    op.execute("DROP FUNCTION IF EXISTS campaign_policy_version_immutable()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_target_segment_campaign_id", table_name="target_segment")
    op.drop_table("target_segment")
    op.drop_index("ix_campaign_policy_version_campaign_id", table_name="campaign_policy_version")
    op.drop_table("campaign_policy_version")
    op.drop_table("campaign")
    # ### end Alembic commands ###
