"""suppression

Revision ID: 614ee9042ca9
Revises: 9c7510908885
Created: 2026-07-29 08:02:23.245044
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "614ee9042ca9"
down_revision: str | None = "9c7510908885"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppression",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("EMAIL", "PERSON", "DOMAIN", "ACCOUNT", name="suppressionscope"),
            nullable=False,
        ),
        sa.Column("identity", sa.String(length=320), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "UNSUBSCRIBE",
                "COMPLAINT",
                "BOUNCE",
                "MANUAL",
                "IMPORT",
                "POLICY",
                name="suppressionsource",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("jurisdiction", sa.String(length=100), nullable=True),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_by", sa.String(length=255), nullable=True),
        sa.Column("lifted_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(lifted_at IS NULL) = (lifted_reason IS NULL)",
            name=op.f("ck_suppression_lift_needs_a_reason"),
        ),
        sa.CheckConstraint(
            "length(trim(identity)) > 0", name=op.f("ck_suppression_identity_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0", name=op.f("ck_suppression_reason_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppression")),
    )
    op.create_index(
        "ix_suppression_scope_identity", "suppression", ["scope", "identity"], unique=False
    )
    # ### end Alembic commands ###

    # Suppression outlives everything (§15.6, §3.5).
    #
    # DELETE is blocked outright: "contact deletion must not delete the suppression record", and
    # more generally a suppression that can be dropped is not a suppression. There are no
    # foreign keys on this table either, so nothing can cascade one away.
    #
    # UNSUBSCRIBE and COMPLAINT can never be lifted — honouring an opt-out is a CAN-SPAM
    # obligation (§15.8), not an operational preference. Other sources (a mistyped domain, a
    # stale import) may be lifted with a recorded reason, because an operator error has to be
    # correctable while an opt-out must not be.
    #
    # The identity, scope, source, reason, and effective time are immutable in all cases: editing
    # them would rewrite history rather than record a new decision.
    op.execute(
        """
        CREATE FUNCTION suppression_is_permanent() RETURNS trigger AS $$
        BEGIN
            -- TRUNCATE must be handled here, before any NEW/OLD comparison: in a
            -- statement-level TRUNCATE trigger both are undefined, so the checks below would
            -- compare NULL to NULL, pass, and let the whole table be erased.
            IF TG_OP IN ('DELETE', 'TRUNCATE') THEN
                RAISE EXCEPTION
                    'suppression records cannot be removed (%); they must survive deletion of '
                    'the contact or account they describe (specification 15.6)', TG_OP
                    USING ERRCODE = 'restrict_violation';
            END IF;

            IF NEW.scope IS DISTINCT FROM OLD.scope
               OR NEW.identity IS DISTINCT FROM OLD.identity
               OR NEW.source IS DISTINCT FROM OLD.source
               OR NEW.reason IS DISTINCT FROM OLD.reason
               OR NEW.effective_at IS DISTINCT FROM OLD.effective_at
            THEN
                RAISE EXCEPTION
                    'suppression identity and provenance are immutable; record a new '
                    'suppression instead (specification 15.6)'
                    USING ERRCODE = 'restrict_violation';
            END IF;

            IF NEW.lifted_at IS NOT NULL
               AND OLD.lifted_at IS NULL
               AND OLD.source IN ('UNSUBSCRIBE', 'COMPLAINT')
            THEN
                RAISE EXCEPTION
                    'an opt-out suppression (%) cannot be lifted (specification 15.6, 15.8)',
                    OLD.source
                    USING ERRCODE = 'restrict_violation';
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER suppression_no_delete_or_rewrite
        BEFORE UPDATE OR DELETE ON suppression
        FOR EACH ROW EXECUTE FUNCTION suppression_is_permanent();
        """
    )
    op.execute(
        """
        CREATE TRIGGER suppression_no_truncate
        BEFORE TRUNCATE ON suppression
        FOR EACH STATEMENT EXECUTE FUNCTION suppression_is_permanent();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS suppression_no_truncate ON suppression")
    op.execute("DROP TRIGGER IF EXISTS suppression_no_delete_or_rewrite ON suppression")
    op.execute("DROP FUNCTION IF EXISTS suppression_is_permanent()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_suppression_scope_identity", table_name="suppression")
    op.drop_table("suppression")
    # ### end Alembic commands ###

    for enum_name in ("suppressionscope", "suppressionsource"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
