"""job queue

Revision ID: 63876c821f52
Revises: e05624f3ae74
Created: 2026-07-29 12:17:41.812465
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "63876c821f52"
down_revision: str | None = "e05624f3ae74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "state",
            sa.Enum("QUEUED", "LEASED", "SUCCEEDED", "RETRY", "DEAD", "CANCELLED", name="jobstate"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leased_by", sa.String(length=255), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'LEASED') = (lease_expires_at IS NOT NULL AND leased_by IS NOT NULL)",
            name=op.f("ck_job_leased_state_needs_a_holder"),
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_job_attempt_count_not_negative")),
        sa.CheckConstraint("length(trim(job_type)) > 0", name=op.f("ck_job_job_type_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index("ix_job_lease_expires_at", "job", ["lease_expires_at"], unique=False)
    op.create_index(
        "ix_job_runnable",
        "job",
        ["priority", "next_run_at"],
        unique=False,
        postgresql_where=sa.text("state IN ('QUEUED', 'RETRY')"),
    )
    op.create_index("ix_job_state", "job", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_state", table_name="job")
    op.drop_index(
        "ix_job_runnable",
        table_name="job",
        postgresql_where=sa.text("state IN ('QUEUED', 'RETRY')"),
    )
    op.drop_index("ix_job_lease_expires_at", table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###

    sa.Enum(name="jobstate").drop(op.get_bind(), checkfirst=True)
