"""audit event table

Revision ID: 6ea1f40a0e13
Revises: 3c526b2ea3ca
Created: 2026-07-29 05:07:10.049048
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "6ea1f40a0e13"
down_revision: str | None = "3c526b2ea3ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "actor_type", sa.Enum("HUMAN", "SERVICE", "SYSTEM", name="actortype"), nullable=False
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("from_state", sa.String(length=50), nullable=True),
        sa.Column("to_state", sa.String(length=50), nullable=True),
        sa.Column("policy_decision", sa.Text(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("app_version", sa.String(length=50), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("schema_version", sa.String(length=50), nullable=True),
        sa.Column("policy_version", sa.String(length=50), nullable=True),
        sa.Column("model_config_version", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "length(trim(action)) > 0", name=op.f("ck_audit_event_action_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(actor_id)) > 0", name=op.f("ck_audit_event_actor_id_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(correlation_id)) > 0", name=op.f("ck_audit_event_correlation_id_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(entity_id)) > 0", name=op.f("ck_audit_event_entity_id_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_event_correlation_id", "audit_event", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_event_entity", "audit_event", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_audit_event_occurred_at", "audit_event", ["occurred_at"], unique=False)
    # ### end Alembic commands ###

    # Append-only, enforced by the database rather than by convention (specification §3.5).
    # An audit trail the application can rewrite is not evidence, and the application user owns
    # this table, so REVOKE would not bind it — a trigger does.
    #
    # TRUNCATE needs its own statement-level trigger: it bypasses row-level triggers entirely,
    # and would otherwise erase the whole trail without tripping anything.
    op.execute(
        """
        CREATE FUNCTION audit_event_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_event is append-only; % is not permitted (specification 3.5)', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_event_no_update_or_delete
        BEFORE UPDATE OR DELETE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION audit_event_append_only();
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_event_no_truncate
        BEFORE TRUNCATE ON audit_event
        FOR EACH STATEMENT EXECUTE FUNCTION audit_event_append_only();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_truncate ON audit_event")
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_update_or_delete ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit_event_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_event_occurred_at", table_name="audit_event")
    op.drop_index("ix_audit_event_entity", table_name="audit_event")
    op.drop_index("ix_audit_event_correlation_id", table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###

    # PostgreSQL enum types outlive their table; without this, re-running the upgrade fails
    # with "type actortype already exists".
    sa.Enum(name="actortype").drop(op.get_bind(), checkfirst=True)
