"""evidence snapshot

Revision ID: 6ed335d539bf
Revises: deff839a67b6
Created: 2026-07-29 09:17:00.165513
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6ed335d539bf"
down_revision: str | None = "deff839a67b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "COMPANY_WEBSITE",
                "INDUSTRY_DIRECTORY",
                "TRADE_SHOW_LISTING",
                "PUBLIC_ANNOUNCEMENT",
                "PROCUREMENT_RECORD",
                "DATA_PROVIDER",
                "CRM_RECORD",
                "LINKEDIN_HUMAN_PROVIDED",
                "MANUAL_ENTRY",
                "SYNTHETIC_FIXTURE",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_url_if_permitted", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supporting_excerpt_or_fact", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_field_or_span", sa.String(length=255), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "MANUAL",
                "STRUCTURED_FIELD",
                "TEXT_SPAN",
                "MODEL_EXTRACTION",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_quality", sa.Enum("HIGH", "MEDIUM", "LOW", name="sourcequality"), nullable=False
        ),
        sa.Column(
            "license_and_retention_class",
            sa.Enum(
                "PUBLIC_UNRESTRICTED",
                "PROVIDER_LICENSED",
                "INTERNAL_ONLY",
                "RESTRICTED",
                name="retentionclass",
            ),
            nullable=False,
        ),
        sa.Column("contains_personal_or_confidential_data", sa.Boolean(), nullable=False),
        sa.Column("expires_or_refresh_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_evidence_snapshot_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "length(supporting_excerpt_or_fact) <= 1000",
            name=op.f("ck_evidence_snapshot_excerpt_within_cap"),
        ),
        sa.CheckConstraint(
            "length(trim(supporting_excerpt_or_fact)) > 0",
            name=op.f("ck_evidence_snapshot_excerpt_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["campaign_candidate.id"],
            name=op.f("fk_evidence_snapshot_candidate_id_campaign_candidate"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_snapshot")),
    )
    op.create_index(
        "ix_evidence_snapshot_candidate_id", "evidence_snapshot", ["candidate_id"], unique=False
    )
    op.create_index(
        "ix_evidence_snapshot_retrieved_at", "evidence_snapshot", ["retrieved_at"], unique=False
    )
    # ### end Alembic commands ###

    # Snapshots are immutable (§9.5).
    #
    # "refresh(candidate_id) -> EvidenceSnapshot[]" produces *new* snapshots; editing one in
    # place would change what a qualification run and any draft citing it were based on, after
    # the decision was recorded.
    #
    # DELETE is deliberately still allowed: `Q-019` will set a retention and deletion policy, and
    # evidence about a person is exactly the category that has to be removable. Suppression is the
    # opposite case and blocks deletion outright — the asymmetry is intentional.
    op.execute(
        """
        CREATE FUNCTION evidence_snapshot_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'evidence_snapshot is immutable; a refresh writes a new snapshot '
                '(specification 9.5, 14.3)'
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER evidence_snapshot_no_rewrite
        BEFORE UPDATE ON evidence_snapshot
        FOR EACH ROW EXECUTE FUNCTION evidence_snapshot_immutable();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS evidence_snapshot_no_rewrite ON evidence_snapshot")
    op.execute("DROP FUNCTION IF EXISTS evidence_snapshot_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_evidence_snapshot_retrieved_at", table_name="evidence_snapshot")
    op.drop_index("ix_evidence_snapshot_candidate_id", table_name="evidence_snapshot")
    op.drop_table("evidence_snapshot")
    # ### end Alembic commands ###

    for enum_name in ("sourcetype", "sourcequality", "extractionmethod", "retentionclass"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
