"""candidate decision

Revision ID: 6fee8153160a
Revises: 55202db10b03
Created: 2026-07-31 10:22:08.422907
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6fee8153160a"
down_revision: str | None = "55202db10b03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_decision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("REJECT", "DEFER", name="decisionkind"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "WRONG_CAMPAIGN",
                "WRONG_ACCOUNT_OR_DUPLICATE",
                "POOR_BUYER_ROLE",
                "WEAK_OR_STALE_EVIDENCE",
                "PRODUCT_NOT_READY",
                "UNSUPPORTED_CLAIM",
                "PERSONALIZATION_NOT_USEFUL",
                "TONE_OR_POSITIONING_PROBLEM",
                "EXISTING_RELATIONSHIP",
                "COMPLIANCE_OR_SUPPRESSION_CONCERN",
                "DEFER_UNTIL_DATE_OR_EVENT",
                name="decisioncategory",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("defer_until_date", sa.Date(), nullable=True),
        sa.Column("defer_until_event", sa.String(length=500), nullable=True),
        sa.Column("decided_by_type", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind <> 'DEFER' OR defer_until_date IS NOT NULL OR (defer_until_event IS NOT NULL AND length(trim(defer_until_event)) > 0)",
            name=op.f("ck_candidate_decision_deferral_has_a_waypoint"),
        ),
        sa.CheckConstraint(
            "kind = 'DEFER' OR (defer_until_date IS NULL AND defer_until_event IS NULL)",
            name=op.f("ck_candidate_decision_only_deferrals_wait"),
        ),
        sa.CheckConstraint(
            "notes IS NULL OR length(trim(notes)) > 0",
            name=op.f("ck_candidate_decision_notes_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["campaign_candidate.id"],
            name=op.f("fk_candidate_decision_candidate_id_campaign_candidate"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_decision")),
    )
    op.create_index(
        op.f("ix_candidate_decision_candidate_id"),
        "candidate_decision",
        ["candidate_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidate_decision_candidate_id"), table_name="candidate_decision")
    op.drop_table("candidate_decision")
    # Dropping the table leaves the enum types behind, and the next `upgrade` then fails with
    # "type already exists" — the trap `ba1a2b2420a4` hit. `checkfirst` so a partial downgrade is
    # still re-runnable.
    sa.Enum(name="decisionkind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="decisioncategory").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
