"""prospect identity

Revision ID: 9c7510908885
Revises: 173f99bbd4a0
Created: 2026-07-29 07:29:13.226237
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9c7510908885"
down_revision: str | None = "173f99bbd4a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain NOT LIKE 'www.%%'", name=op.f("ck_account_domain_has_no_www_prefix")
        ),
        sa.CheckConstraint(
            "position('/' in domain) = 0", name=op.f("ck_account_domain_has_no_path")
        ),
        sa.CheckConstraint(
            "country_code IS NULL OR country_code = upper(country_code)",
            name=op.f("ck_account_country_code_is_uppercase"),
        ),
        sa.CheckConstraint("domain = lower(domain)", name=op.f("ck_account_domain_is_lowercase")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_account_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
        sa.UniqueConstraint("domain", name="uq_account_domain"),
    )
    op.create_table(
        "crm_mapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Enum("FAKE", "HUBSPOT", name="crmprovider"), nullable=False),
        sa.Column(
            "record_type", sa.Enum("ACCOUNT", "CONTACT", name="mappedrecordtype"), nullable=False
        ),
        sa.Column("internal_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(external_id)) > 0", name=op.f("ck_crm_mapping_external_id_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crm_mapping")),
        sa.UniqueConstraint(
            "provider", "record_type", "external_id", name="uq_crm_mapping_external"
        ),
        sa.UniqueConstraint(
            "provider", "record_type", "internal_id", name="uq_crm_mapping_internal"
        ),
    )
    op.create_index("ix_crm_mapping_internal_id", "crm_mapping", ["internal_id"], unique=False)
    op.create_table(
        "contact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(full_name)) > 0", name=op.f("ck_contact_full_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_contact_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_index("ix_contact_account_id", "contact", ["account_id"], unique=False)
    op.create_table(
        "contact_point",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("EMAIL", "PHONE", "LINKEDIN_URL", name="contactpointtype"),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=320), nullable=False),
        sa.Column(
            "verification_state",
            sa.Enum("UNVERIFIED", "VERIFIED", "INVALID", name="verificationstate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type <> 'EMAIL' OR value = lower(value)",
            name=op.f("ck_contact_point_email_value_is_lowercase"),
        ),
        sa.CheckConstraint(
            "length(trim(value)) > 0", name=op.f("ck_contact_point_value_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_point_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_point")),
        sa.UniqueConstraint("type", "value", name="uq_contact_point_type_value"),
    )
    op.create_index("ix_contact_point_contact_id", "contact_point", ["contact_id"], unique=False)
    op.create_index("ix_contact_point_value", "contact_point", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contact_point_value", table_name="contact_point")
    op.drop_index("ix_contact_point_contact_id", table_name="contact_point")
    op.drop_table("contact_point")
    op.drop_index("ix_contact_account_id", table_name="contact")
    op.drop_table("contact")
    op.drop_index("ix_crm_mapping_internal_id", table_name="crm_mapping")
    op.drop_table("crm_mapping")
    op.drop_table("account")
    # ### end Alembic commands ###

    # Enum types outlive their tables; without this a re-upgrade fails with "type already
    # exists". See docs/development.md.
    for enum_name in ("contactpointtype", "verificationstate", "crmprovider", "mappedrecordtype"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
