"""identity and access tables

Revision ID: ba1a2b2420a4
Revises: f5eafa7d8ad9
Created: 2026-07-31 04:35:24.606138
"""

import uuid
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "ba1a2b2420a4"
down_revision: str | None = "f5eafa7d8ad9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Fixed namespace for deterministic role IDs. A constant, never regenerated: changing it would
#: renumber every role and orphan every grant that referenced one.
ROLE_NAMESPACE = uuid.UUID("6f1f5a1e-1c4e-4f2a-9a3e-0d7b5c2a8e10")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_app_user_ck_app_user_email_lowercase")
        ),
        sa.CheckConstraint(
            "length(trim(display_name)) > 0",
            name=op.f("ck_app_user_ck_app_user_display_name_present"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name="uq_app_user_email"),
        sa.UniqueConstraint("subject", name="uq_app_user_subject"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("responsibility", sa.Text(), nullable=False),
        sa.Column("human_only", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("id", "human_only", name="uq_role_id_human_only"),
        sa.UniqueConstraint("key", name="uq_role_key"),
    )
    op.create_table(
        "service_identity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name=op.f("ck_service_identity_ck_service_identity_name_present"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_identity")),
        sa.UniqueConstraint("name", name="uq_service_identity_name"),
    )
    op.create_table(
        "channel_identity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Enum("WHATSAPP", "IMESSAGE", name="channeltype"), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(address)) > 0",
            name=op.f("ck_channel_identity_ck_channel_identity_address_present"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_channel_identity_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_identity")),
        sa.UniqueConstraint("channel", "address", name="uq_channel_identity_address"),
    )
    op.create_table(
        "service_identity_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_identity_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("human_only", sa.Boolean(), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "human_only = false",
            name=op.f("ck_service_identity_role_ck_service_role_not_human_only"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id", "human_only"],
            ["role.id", "role.human_only"],
            name="fk_service_role_role_not_human_only",
        ),
        sa.ForeignKeyConstraint(
            ["service_identity_id"],
            ["service_identity.id"],
            name=op.f("fk_service_identity_role_service_identity_id_service_identity"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_identity_role")),
        sa.UniqueConstraint("service_identity_id", "role_id", name="uq_service_identity_role"),
    )
    op.create_table(
        "user_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_user_role_role_id_role")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_user_role_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role")),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    # ### end Alembic commands ###

    _seed_roles()


#: The six roles of §12.1 and whether only a human may hold each.
#:
#: Duplicated from `app.identity.models` on purpose. A migration that imported application code
#: would seed whatever that code says *today*, so replaying history would produce a different
#: database than it did originally — the one thing a migration must never do. The literal here is
#: the historical fact; `tests/test_identity.py` asserts the two still agree, so drift is a test
#: failure rather than a silent divergence.
SEEDED_ROLES: tuple[tuple[str, str, bool], ...] = (
    (
        "product_claim_owner",
        "Approves product specifications, readiness, outbound claims, and review dates",
        True,
    ),
    (
        "campaign_sales_owner",
        "Defines ICP, opportunity goals, exclusions, volume, and outreach policy",
        True,
    ),
    (
        "operator_reviewer",
        "Reviews candidates, evidence, exact message revisions, and corrections",
        True,
    ),
    ("reply_owner", "Receives and handles positive or substantive replies", True),
    (
        "system_administrator",
        "Manages identity, integrations, credentials, limits, pauses, and recovery",
        True,
    ),
    # The one role a service may hold: reading status authorizes nothing.
    ("viewer", "Reads status and reports without making changes", False),
)


def _seed_roles() -> None:
    """Insert the six roles. Reference data, so it belongs in the migration, not in a seeder.

    A role that only exists after someone remembers to run a script is a role an authorization
    check can fail to find at 3am. Deterministic UUIDs (`uuid5` over the role key) so a database
    rebuilt from migrations has the same role IDs as the one before it — a `user_role` row dumped
    from staging and loaded into a fresh database would otherwise point at nothing.
    """
    connection = op.get_bind()
    for key, responsibility, human_only in SEEDED_ROLES:
        connection.execute(
            sa.text(
                "INSERT INTO role (id, key, responsibility, human_only, created_at, updated_at) "
                "VALUES (:id, :key, :responsibility, :human_only, now(), now())"
            ),
            {
                "id": uuid.uuid5(ROLE_NAMESPACE, key),
                "key": key,
                "responsibility": responsibility,
                "human_only": human_only,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role")
    op.drop_table("service_identity_role")
    op.drop_table("channel_identity")
    op.drop_table("service_identity")
    op.drop_table("role")
    op.drop_table("app_user")
    # ### end Alembic commands ###

    # Dropping the table does not drop the type. Without this, `downgrade` then `upgrade` fails
    # on `CREATE TYPE channeltype ... already exists` — which is how this was found, because
    # `process.md` §5 requires a migration to reverse *and re-apply*.
    sa.Enum(name="channeltype").drop(op.get_bind(), checkfirst=True)
