"""model run

Revision ID: c1b7f16c23f2
Revises: e94c35cb931f
Created: 2026-07-30 18:52:23.346010
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "c1b7f16c23f2"
down_revision: str | None = "e94c35cb931f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("schema_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_config_version_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        # `modelprovider` is created by the `model_config_version` migration; a second CREATE TYPE
        # would fail with "type already exists" (docs/development.md).
        sa.Column(
            "provider", postgresql.ENUM(name="modelprovider", create_type=False), nullable=False
        ),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "SUCCEEDED",
                "REFUSED_BUDGET",
                "PROVIDER_ERROR",
                "INVALID_OUTPUT",
                name="modelrunoutcome",
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(outcome = 'SUCCEEDED') = (failure_reason IS NULL)",
            name=op.f("ck_model_run_failure_reason_matches_outcome"),
        ),
        sa.CheckConstraint(
            "outcome <> 'REFUSED_BUDGET' OR (input_tokens = 0 AND output_tokens = 0 AND cost_usd = 0)",
            name=op.f("ck_model_run_a_refused_run_spends_nothing"),
        ),
        sa.CheckConstraint("cost_usd >= 0", name=op.f("ck_model_run_cost_not_negative")),
        sa.CheckConstraint(
            "input_tokens >= 0", name=op.f("ck_model_run_input_tokens_not_negative")
        ),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_model_run_latency_not_negative")),
        sa.CheckConstraint(
            "length(trim(task_name)) > 0", name=op.f("ck_model_run_task_name_not_blank")
        ),
        sa.CheckConstraint(
            "output_tokens >= 0", name=op.f("ck_model_run_output_tokens_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["model_config_version_id"],
            ["model_config_version.id"],
            name=op.f("fk_model_run_model_config_version_id_model_config_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_version.id"],
            name=op.f("fk_model_run_policy_version_id_policy_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_version.id"],
            name=op.f("fk_model_run_prompt_version_id_prompt_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schema_version_id"],
            ["schema_version.id"],
            name=op.f("fk_model_run_schema_version_id_schema_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_run")),
    )
    op.create_index("ix_model_run_campaign_id", "model_run", ["campaign_id"], unique=False)
    op.create_index("ix_model_run_started_at", "model_run", ["started_at"], unique=False)
    op.create_index(
        "ix_model_run_task_name_started_at", "model_run", ["task_name", "started_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_run_task_name_started_at", table_name="model_run")
    op.drop_index("ix_model_run_started_at", table_name="model_run")
    op.drop_index("ix_model_run_campaign_id", table_name="model_run")
    op.drop_table("model_run")
    # `drop_table` leaves the enum type behind, so a later re-upgrade fails. `modelprovider` is
    # NOT dropped here — it belongs to the migration that created it (docs/development.md).
    sa.Enum(name="modelrunoutcome").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
