"""approver columns become foreign keys to app_user.email

Revision ID: c41d7b90ae52
Revises: 8752f60aa338
Created: 2026-08-01 04:10:00.000000

T-136b (§14.4, §12.2, ADR-024). Four approver columns stop being free text: an approver can no
longer be a typo, and a user with approval history can no longer be deleted.

**Hand-written, not autogenerated.** The constraints themselves autogenerate fine; the check
below does not, and without it this migration would fail with a bare foreign-key violation
naming a constraint the reader has never heard of. §12.2 also forbids the alternative — nulling
an approver the migration cannot resolve would delete attribution to make a schema change
convenient, and an approval nobody can attribute is worse than a migration that stops.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c41d7b90ae52"
down_revision: str | None = "8752f60aa338"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: table -> constraint name. One name per column so a violation says which record refused.
APPROVER_COLUMNS: tuple[tuple[str, str], ...] = (
    ("product_status_version", "fk_product_status_version_approved_by_app_user"),
    ("approved_claim", "fk_approved_claim_approved_by_app_user"),
    ("approved_claim_set", "fk_approved_claim_set_approved_by_app_user"),
    ("campaign_policy_version", "fk_campaign_policy_version_approved_by_app_user"),
)


def unresolvable_approvers(connection: sa.engine.Connection) -> dict[str, list[str]]:
    """Approver values with no `app_user` row, per table.

    Takes the connection rather than calling `op.get_bind()` itself so a test can run it: the
    condition it guards needs rows that the constraint below makes uninsertable, which is only
    reachable by dropping the constraint inside a transaction. A negative control that removed
    the call did not fail anything until this was extracted — that is the finding, not a pass.
    """
    found: dict[str, list[str]] = {}
    for table, _ in APPROVER_COLUMNS:
        # The table name is interpolated from the literal tuple above, never from input.
        orphaned = (
            connection.execute(
                sa.text(
                    f"SELECT DISTINCT approved_by FROM {table} "
                    "WHERE approved_by NOT IN (SELECT email FROM app_user)"
                )
            )
            .scalars()
            .all()
        )
        if orphaned:
            found[table] = sorted(orphaned)
    return found


def _refuse_unresolvable_approvers() -> None:
    """Stop before the constraints, naming the rows and the fix.

    A database seeded before `T-136a` holds approver strings that match no user — the seeder used
    to write `SYNTHETIC-approver`. Re-seed (`docker compose down -v` then `alembic upgrade head`
    and `python -m app.cli seed_synthetic`) rather than editing rows by hand.
    """
    for table, orphaned in unresolvable_approvers(op.get_bind()).items():
        raise RuntimeError(
            f"{table}.approved_by holds {len(orphaned)} value(s) with no app_user row: "
            f"{orphaned}. Create those users, or re-seed a local database — see T-136a. "
            f"Nulling them would delete attribution the specification requires to be "
            f"immutable (§12.2)."
        )


def upgrade() -> None:
    _refuse_unresolvable_approvers()
    for table, name in APPROVER_COLUMNS:
        op.create_foreign_key(
            name,
            table,
            "app_user",
            ["approved_by"],
            ["email"],
            ondelete="RESTRICT",
            onupdate="CASCADE",
        )


def downgrade() -> None:
    for table, name in APPROVER_COLUMNS:
        op.drop_constraint(name, table, type_="foreignkey")
