"""campaign candidate

Revision ID: deff839a67b6
Revises: 614ee9042ca9
Created: 2026-07-29 08:40:00.956642
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "deff839a67b6"
down_revision: str | None = "614ee9042ca9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_candidate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "IMPORTED",
                "ELIGIBLE",
                "INELIGIBLE",
                "RESEARCH_PENDING",
                "RESEARCHED",
                "REVIEW_PENDING",
                "APPROVED",
                "REJECTED",
                "DEFERRED",
                "INVALIDATED",
                name="campaigncandidatestate",
            ),
            nullable=False,
        ),
        sa.Column("ineligible_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'INELIGIBLE' OR ineligible_reason IS NOT NULL",
            name=op.f("ck_campaign_candidate_ineligible_needs_a_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_campaign_candidate_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("fk_campaign_candidate_campaign_id_campaign"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_campaign_candidate_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_candidate")),
        sa.UniqueConstraint(
            "campaign_id",
            "account_id",
            "contact_id",
            name="uq_campaign_candidate_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_campaign_candidate_account_id", "campaign_candidate", ["account_id"], unique=False
    )
    op.create_index(
        "ix_campaign_candidate_campaign_id", "campaign_candidate", ["campaign_id"], unique=False
    )
    op.create_index("ix_campaign_candidate_state", "campaign_candidate", ["state"], unique=False)
    # ### end Alembic commands ###

    # The identity triple is immutable (§8.1).
    #
    # Repointing a candidate at a different campaign, account, or contact would silently reassign
    # every evidence snapshot, score, and review decision already recorded against it — the audit
    # trail would describe work done on someone else. Create a new membership instead.
    #
    # State itself stays writable at the database level on purpose: legality is a *sequence*
    # question that belongs in `app.core.lifecycles`, and duplicating the transition table in
    # plpgsql would give two rule sets to keep in step. `transition()` is the only supported
    # path, and the audit trail shows any write that skipped it.
    op.execute(
        """
        CREATE FUNCTION campaign_candidate_identity_immutable() RETURNS trigger AS $$
        BEGIN
            IF NEW.campaign_id IS DISTINCT FROM OLD.campaign_id
               OR NEW.account_id IS DISTINCT FROM OLD.account_id
               OR NEW.contact_id IS DISTINCT FROM OLD.contact_id
            THEN
                RAISE EXCEPTION
                    'campaign_candidate identity (campaign, account, contact) is immutable; '
                    'create a new membership instead (specification 8.1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER campaign_candidate_no_identity_rewrite
        BEFORE UPDATE ON campaign_candidate
        FOR EACH ROW EXECUTE FUNCTION campaign_candidate_identity_immutable();
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS campaign_candidate_no_identity_rewrite ON campaign_candidate"
    )
    op.execute("DROP FUNCTION IF EXISTS campaign_candidate_identity_immutable()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_campaign_candidate_state", table_name="campaign_candidate")
    op.drop_index("ix_campaign_candidate_campaign_id", table_name="campaign_candidate")
    op.drop_index("ix_campaign_candidate_account_id", table_name="campaign_candidate")
    op.drop_table("campaign_candidate")
    # ### end Alembic commands ###

    sa.Enum(name="campaigncandidatestate").drop(op.get_bind(), checkfirst=True)
