"""versioned artefacts

Revision ID: e05624f3ae74
Revises: 4ad849bbfecc
Created: 2026-07-29 11:39:09.667560
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "e05624f3ae74"
down_revision: str | None = "4ad849bbfecc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_config_version",
        sa.Column("provider", sa.Enum("FAKE", name="modelprovider"), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_model_config_version_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_model_config_version_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "length(trim(created_by)) > 0",
            name=op.f("ck_model_config_version_created_by_not_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(key)) > 0", name=op.f("ck_model_config_version_key_not_blank")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_model_config_version_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_config_version")),
        sa.UniqueConstraint("key", "version", name="uq_model_config_version_key_version"),
    )
    op.create_index("ix_model_config_version_key", "model_config_version", ["key"], unique=False)
    op.create_table(
        "policy_version",
        sa.Column("policy_type", sa.String(length=100), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_version_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_policy_version_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "length(trim(created_by)) > 0", name=op.f("ck_policy_version_created_by_not_blank")
        ),
        sa.CheckConstraint("length(trim(key)) > 0", name=op.f("ck_policy_version_key_not_blank")),
        sa.CheckConstraint("version > 0", name=op.f("ck_policy_version_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_version")),
        sa.UniqueConstraint("key", "version", name="uq_policy_version_key_version"),
    )
    op.create_index("ix_policy_version_key", "policy_version", ["key"], unique=False)
    op.create_table(
        "prompt_version",
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_prompt_version_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_prompt_version_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "length(trim(created_by)) > 0", name=op.f("ck_prompt_version_created_by_not_blank")
        ),
        sa.CheckConstraint("length(trim(key)) > 0", name=op.f("ck_prompt_version_key_not_blank")),
        sa.CheckConstraint("version > 0", name=op.f("ck_prompt_version_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_version")),
        sa.UniqueConstraint("key", "version", name="uq_prompt_version_key_version"),
    )
    op.create_index("ix_prompt_version_key", "prompt_version", ["key"], unique=False)
    op.create_table(
        "schema_version",
        sa.Column("json_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_schema_version_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_schema_version_effective_window_ordered"),
        ),
        sa.CheckConstraint(
            "length(trim(created_by)) > 0", name=op.f("ck_schema_version_created_by_not_blank")
        ),
        sa.CheckConstraint("length(trim(key)) > 0", name=op.f("ck_schema_version_key_not_blank")),
        sa.CheckConstraint("version > 0", name=op.f("ck_schema_version_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_version")),
        sa.UniqueConstraint("key", "version", name="uq_schema_version_key_version"),
    )
    op.create_index("ix_schema_version_key", "schema_version", ["key"], unique=False)
    # ### end Alembic commands ###

    # One effective version per key per instant, and immutable once written (§17.5, GP-09).
    #
    # The exclusion constraint is the same tool product readiness uses (T-013): an application
    # check would let two concurrent writers both commit overlapping windows, leaving a model run
    # attributable to two different prompts.
    #
    # The immutability trigger matters more here than almost anywhere else: editing a prompt or
    # schema in place would silently rewrite the basis of every model run that already cites it,
    # so the run would claim a version whose content had since changed. `effective_to` stays
    # mutable — closing a window is how the next version takes over, and it changes no content.
    for table in ("prompt_version", "schema_version", "model_config_version", "policy_version"):
        op.execute(
            f"""
            ALTER TABLE {table}
            ADD CONSTRAINT ex_{table}_no_overlap
            EXCLUDE USING gist (
                key WITH =,
                tstzrange(effective_from, effective_to, '[)') WITH &&
            )
            """
        )
        op.execute(
            f"""
            CREATE FUNCTION {table}_immutable() RETURNS trigger AS $$
            BEGIN
                IF NEW.key IS DISTINCT FROM OLD.key
                   OR NEW.version IS DISTINCT FROM OLD.version
                   OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
                   OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
                   OR NEW.created_by IS DISTINCT FROM OLD.created_by
                THEN
                    RAISE EXCEPTION
                        'a versioned artefact is immutable once written; publish the next '
                        'version instead (specification 17.5, GP-09)'
                        USING ERRCODE = 'restrict_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_rewrite
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION {table}_immutable();
            """
        )


def downgrade() -> None:
    for table in ("prompt_version", "schema_version", "model_config_version", "policy_version"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_rewrite ON {table}")
        op.execute(f"DROP FUNCTION IF EXISTS {table}_immutable()")
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS ex_{table}_no_overlap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_schema_version_key", table_name="schema_version")
    op.drop_table("schema_version")
    op.drop_index("ix_prompt_version_key", table_name="prompt_version")
    op.drop_table("prompt_version")
    op.drop_index("ix_policy_version_key", table_name="policy_version")
    op.drop_table("policy_version")
    op.drop_index("ix_model_config_version_key", table_name="model_config_version")
    op.drop_table("model_config_version")
    # ### end Alembic commands ###

    # Enum types outlive their tables; without this a re-upgrade fails with "type already
    # exists". See docs/development.md.
    sa.Enum(name="modelprovider").drop(op.get_bind(), checkfirst=True)
