"""prospect import batch

Revision ID: e94c35cb931f
Revises: 224564968fc6
Created: 2026-07-30 16:21:01.312966
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "e94c35cb931f"
down_revision: str | None = "224564968fc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("reused_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_import_batch_content_hash_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "created_count + reused_count + rejected_count = row_count",
            name=op.f("ck_import_batch_row_outcomes_account_for_every_row"),
        ),
        sa.CheckConstraint(
            "created_count >= 0", name=op.f("ck_import_batch_created_count_not_negative")
        ),
        sa.CheckConstraint(
            "length(trim(source_name)) > 0", name=op.f("ck_import_batch_source_name_not_blank")
        ),
        sa.CheckConstraint(
            "rejected_count >= 0", name=op.f("ck_import_batch_rejected_count_not_negative")
        ),
        sa.CheckConstraint(
            "reused_count >= 0", name=op.f("ck_import_batch_reused_count_not_negative")
        ),
        sa.CheckConstraint("row_count >= 0", name=op.f("ck_import_batch_row_count_not_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batch")),
        sa.UniqueConstraint("content_hash", name="uq_import_batch_content_hash"),
    )
    op.create_index("ix_import_batch_created_at", "import_batch", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_import_batch_created_at", table_name="import_batch")
    op.drop_table("import_batch")
    # ### end Alembic commands ###
