"""transactional outbox

Revision ID: f09d40b96a8b
Revises: 90aa0487c939
Created: 2026-07-29 14:59:23.910151
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f09d40b96a8b"
down_revision: str | None = "90aa0487c939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "state",
            sa.Enum("PENDING", "DISPATCHING", "DISPATCHED", "FAILED", name="outboxstate"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "idempotency_key ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_outbox_event_outbox_idempotency_key_is_sha256_hex"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_outbox_event_outbox_attempt_count_not_negative")
        ),
        sa.CheckConstraint(
            "length(trim(event_type)) > 0", name=op.f("ck_outbox_event_outbox_event_type_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_event_idempotency_key"),
    )
    op.create_index(
        "ix_outbox_pending",
        "outbox_event",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("state = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        "ix_outbox_pending",
        table_name="outbox_event",
        postgresql_where=sa.text("state = 'PENDING'"),
    )
    op.drop_table("outbox_event")
    # `drop_table` leaves the enum type behind, so a later re-upgrade fails with
    # "type outboxstate already exists". See docs/development.md.
    sa.Enum(name="outboxstate").drop(op.get_bind(), checkfirst=True)
