"""qualification run

Revision ID: f5eafa7d8ad9
Revises: c1b7f16c23f2
Created: 2026-07-30 20:20:04.942189
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f5eafa7d8ad9"
down_revision: str | None = "c1b7f16c23f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qualification_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_type", sa.String(length=50), nullable=False),
        sa.Column("evidence_completeness", sa.String(length=20), nullable=False),
        sa.Column("source_quality", sa.String(length=20), nullable=False),
        sa.Column("product_fit", sa.Integer(), nullable=False),
        sa.Column("buyer_relevance", sa.Integer(), nullable=False),
        sa.Column("timing", sa.Integer(), nullable=False),
        sa.Column("commercial_scale", sa.Integer(), nullable=False),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column("model_requested_no_review", sa.Boolean(), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "buyer_relevance BETWEEN 0 AND 5",
            name=op.f("ck_qualification_run_buyer_relevance_in_range"),
        ),
        sa.CheckConstraint(
            "commercial_scale BETWEEN 0 AND 5",
            name=op.f("ck_qualification_run_commercial_scale_in_range"),
        ),
        sa.CheckConstraint(
            "human_review_required",
            name=op.f("ck_qualification_run_human_review_is_always_required"),
        ),
        sa.CheckConstraint(
            "product_fit BETWEEN 0 AND 5", name=op.f("ck_qualification_run_product_fit_in_range")
        ),
        sa.CheckConstraint(
            "timing BETWEEN 0 AND 5", name=op.f("ck_qualification_run_timing_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["campaign_candidate.id"],
            name=op.f("fk_qualification_run_candidate_id_campaign_candidate"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_run.id"],
            name=op.f("fk_qualification_run_model_run_id_model_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualification_run")),
    )
    op.create_index(
        "ix_qualification_run_candidate_id", "qualification_run", ["candidate_id"], unique=False
    )
    op.create_index(
        "ix_qualification_run_opportunity_type",
        "qualification_run",
        ["opportunity_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_qualification_run_opportunity_type", table_name="qualification_run")
    op.drop_index("ix_qualification_run_candidate_id", table_name="qualification_run")
    op.drop_table("qualification_run")
    # ### end Alembic commands ###
