import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { NonLocalApiBaseUrl, apiBaseUrl, assertLocal } from "../lib/api";

/**
 * The dashboard's types come from the backend, and drift fails here rather than at runtime
 * (T-060b; §23).
 *
 * The chain is: FastAPI application -> `openapi.json` -> `lib/api-types.ts`. Each arrow has a
 * test. This file owns the second one; the first is
 * `backend/tests/test_fixtures.py::test_the_committed_openapi_document_matches_the_application`,
 * which is the only side that can ask the Python application what it exposes.
 *
 * Without both, either arrow can rot silently: a backend change nobody re-exports leaves a stale
 * document that every frontend check still passes against, and a hand-edited type file compiles
 * perfectly while describing an API that does not exist.
 */

const ROOT = join(import.meta.dirname, "..");
const GENERATED = join(ROOT, "lib", "api-types.ts");

const normalize = (source: string): string => source.replace(/\r\n/g, "\n").trim();

/**
 * How long the regeneration below may take (T-150).
 *
 * The generator spawns a Node process that parses `openapi.json` and emits ~42 KB of TypeScript.
 * Measured at **2.0–2.4 s** on an idle machine — comfortably inside Vitest's 5 s default, which is
 * why this looked fine for four cycles. Under a full parallel run it is not: six other files hold
 * `jsdom` environments, and the subprocess competes with them for CPU. It crossed 5 s twice in
 * twelve consecutive runs, and the failure was a **test timeout, not a mismatch** — the comparison
 * never ran, so nothing about drift was ever wrong.
 *
 * Ten times the measured cost. Raising it does not weaken the assertion: what is being compared,
 * and what would fail, are unchanged. It stops a correct test failing for a reason that has
 * nothing to do with the thing it checks — which is worse than a slow test, because a check that
 * cries wolf is one people learn to re-run rather than read.
 */
const GENERATION_TIMEOUT_MS = 30_000;

describe("the generated client", () => {
  it(
    "matches a fresh generation from the committed document",
    () => {
      const committed = readFileSync(GENERATED, "utf8");

      // Generated to stdout rather than over the checked-in file: a test that rewrites the thing
      // it is checking would pass on the second run no matter what happened on the first.
      //
      // Run through `process.execPath` and the generator's own entry point rather than `npx`:
      // Node refuses to spawn a `.cmd` shim without a shell, and reaching for `shell: true` to
      // work around that would put a shell in the loop for no benefit.
      const fresh = execFileSync(
      process.execPath,
      [join(ROOT, "node_modules", "openapi-typescript", "bin", "cli.js"), "openapi.json"],
      { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
      );

      // Line endings normalized: the generator writes CRLF through `-o` on Windows and LF to
      // stdout, and a drift test that failed on that would be a drift test nobody trusted.
      expect(normalize(committed)).toBe(normalize(fresh));
    },
    GENERATION_TIMEOUT_MS,
  );

  it("says it is generated", () => {
    const committed = readFileSync(GENERATED, "utf8");

    expect(committed).toContain("auto-generated by openapi-typescript");
    expect(committed).toContain("Do not make direct changes");
  });

  it("describes the endpoints the backend exposes", () => {
    // A guard on the guard: an empty or truncated file would make the comparison above pass
    // against an equally empty regeneration.
    const committed = readFileSync(GENERATED, "utf8");

    expect(committed).toContain('"/healthz"');
    expect(committed).toContain('"/readyz"');
  });
});

describe("the API base URL", () => {
  it("defaults to the local backend", () => {
    expect(apiBaseUrl.hostname).toBe("localhost");
    expect(apiBaseUrl.port).toBe("8000");
  });

  it.each(["localhost", "127.0.0.1"])("accepts %s", (host) => {
    expect(assertLocal(`http://${host}:8000`).hostname).toBe(host);
  });

  it.each([
    "https://api.example.com",
    "http://192.0.2.10:8000",
    "https://matrixpower.example.net/api",
  ])("refuses %s", (url) => {
    // §2 item 14: a code path existing is not a reason to reach a real environment. Pointing the
    // dashboard at one is a deployment decision, not a configuration edit.
    expect(() => assertLocal(url)).toThrow(NonLocalApiBaseUrl);
  });

  it("refuses something that is not a URL at all", () => {
    expect(() => assertLocal("not-a-url")).toThrow(NonLocalApiBaseUrl);
  });
});
