/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current session, or 401
         * @description Who the caller is. `401` when nobody.
         *
         *     Not `requires(...)`: there is no permission to hold here — the question is whether a session
         *     resolves at all, and every role may ask it. The dashboard uses this to tell "signed out" from
         *     "signed in without the role", which are different screens.
         */
        get: operations["read_session_api_auth_session_get"];
        put?: never;
        post?: never;
        /**
         * Sign out, revoking the current session
         * @description Revoke the caller's own session, and only their own.
         *
         *     A caller with no session gets `204` rather than `401`: signing out when already signed out is
         *     the state they asked for, and answering `401` would make a dashboard sign-out button fail for
         *     a reviewer whose session had just expired.
         */
        delete: operations["sign_out_api_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/stub-sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in as an existing local user (local environment only)
         * @description Issue a session for a known local user. Verifies nothing; refused outside `local`.
         *
         *     The environment check is the first statement on purpose — see the module docstring. An unknown
         *     email is `404` and creates nobody: the roster is `Q-005` and `Q-026`, not whoever can reach
         *     this port.
         */
        post: operations["stub_sign_in_endpoint_api_auth_stub_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/approvals/{approval_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke an approval so it can never dispatch
         * @description Withdraw an approval (§8.2's `approved -> revoked`, §17.6).
         *
         *     **`APPROVE_MESSAGE`, the same permission that granted it.** Withdrawing an authorization is
         *     the same authority as giving one — a role that could revoke but not approve could stop any
         *     outreach it disliked, and one that could approve but not revoke could not undo its own
         *     mistake.
         *
         *     A reason is required with no default: §17.6 wants operational actions explicable, and a
         *     revocation nobody can explain later is one a reviewer cannot distinguish from a fault.
         */
        post: operations["revoke_approval_endpoint_api_review_approvals__approval_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/attention/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Approvals that no longer authorize a send
         * @description §7.5's flag. A read, so `requires` rather than `requires_bearer`.
         *
         *     Only approvals still in `approved` are scanned: one already revoked or rejected is not an
         *     attention item — somebody dealt with it — and listing them would bury the ones nobody has
         *     looked at.
         */
        get: operations["approvals_needing_attention_endpoint_api_review_attention_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidates awaiting review
         * @description Candidates waiting on a person, oldest first.
         *
         *     ``principal`` is unused in the body and required in the signature: it is what runs the
         *     authorization, and naming it makes that visible at the endpoint rather than hidden in a
         *     decorator someone could remove without the route looking different.
         */
        get: operations["list_candidates_api_review_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the review card shows for one candidate
         * @description §12.3 items 1-5 for one candidate. Returns nothing that acts.
         */
        get: operations["get_candidate_api_review_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates/{candidate_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a candidate for outreach to an exact recipient
         * @description §8.3 step 9: candidate approval, which queues the drafting job.
         *
         *     **`APPROVE_CANDIDATE`, not `CORRECT_CANDIDATE`.** §7.4 puts this at tier 4 — the approval that
         *     lets an external effect happen at all — while rejecting and deferring are tier-3 reversible
         *     internal changes. The two are deliberately different permissions, so a role that may tidy the
         *     queue cannot start outreach.
         *
         *     **The recipient is checked against this candidate's contact.** A contact point id is just a
         *     UUID; without this, an approver could name an address belonging to somebody else entirely and
         *     the drafting job would write to it. §8.1 makes the candidate a `campaign + account + contact`
         *     membership, so "this candidate's contact" is exactly the right scope.
         *
         *     **An unverified address is refused.** Approving one would put the reputation risk ADR-008
         *     exists to manage onto a guess about whether the mailbox is real.
         *
         *     Nothing is sent. Approval queues drafting; shadow mode holds, and live sending stays behind
         *     **G-07**.
         */
        post: operations["approve_candidate_endpoint_api_review_candidates__candidate_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates/{candidate_id}/defer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Defer a candidate until a date or an event
         * @description §8.2's `review_pending -> deferred`. A deferral with no waypoint is `409`, not a candidate
         *     that quietly leaves review with nothing to bring it back.
         */
        post: operations["defer_candidate_endpoint_api_review_candidates__candidate_id__defer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a candidate, with a structured reason
         * @description §8.2's `review_pending -> rejected`, with §10.6's category recorded against it.
         */
        post: operations["reject_candidate_endpoint_api_review_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/candidates/{candidate_id}/request-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for more evidence about a candidate that stays in review
         * @description ADR-022: this queues an evidence pass and moves the candidate nowhere.
         *
         *     §8.2 offers no edge from `review_pending` back to `research_pending`, so unlike reject and
         *     defer this decision leaves the candidate exactly where the reviewer is looking at it — the
         *     response still carries `state` so a dashboard can show that rather than assume it.
         *
         *     A pass already in flight is `409` with the reason, not a second queued pass: a reviewer who
         *     clicks twice wants one more pass, not two.
         */
        post: operations["request_more_research_endpoint_api_review_candidates__candidate_id__request_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revisions awaiting review
         * @description Revisions waiting on a person, longest-waiting first.
         */
        get: operations["list_revisions_api_review_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/revisions/{revision_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve an exact message revision for an exact recipient
         * @description §11.3 step 1, then the transaction.
         *
         *     Every refusal below happens before `approve_message` is called, so a rejected request writes
         *     nothing at all — there is no partial state for the caller to undo, and no audit event claiming
         *     an approval that did not happen.
         */
        post: operations["approve_message_endpoint_api_review_revisions__revision_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/revisions/{revision_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit a draft, creating the next immutable revision
         * @description §10.5: an edit creates revision N+1 and leaves N exactly as it was.
         *
         *     `requires_bearer`, not `requires`: this is a state-changing route, and a cookie is what a
         *     CSRF attack rides on. See `identity.dependencies` — the exposure is removed until `T-070`
         *     adds real protection, rather than accepted on trust.
         *
         *     The actor comes from the session (§12.2), never from the request body. Committed here rather
         *     than by the caller: the retired approval, the superseded revision, the new one, and its
         *     validation are one decision, and a half-applied edit is the state this must never leave.
         */
        post: operations["edit_revision_endpoint_api_review_revisions__revision_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Deliberately touches no dependency, so it stays up while they are down.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness. Fails closed: anything other than a successful round-trip is 503.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApproveMessageRequest
         * @description What the approver confirms (§11.3 steps 1-2).
         */
        ApproveMessageRequest: {
            /**
             * Recipient Contact Point Id
             * Format: uuid
             */
            recipient_contact_point_id: string;
            /** Record Version */
            record_version?: string | null;
        };
        /**
         * ApproveMessageResponse
         * @description What was approved, and what it produced.
         */
        ApproveMessageResponse: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /**
             * Message Revision Id
             * Format: uuid
             */
            message_revision_id: string;
            /** Recipient */
            recipient: string;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            /** Revision State */
            revision_state: string;
            /**
             * Send Command Id
             * Format: uuid
             */
            send_command_id: string;
            /** What Happens Next */
            what_happens_next: string;
        };
        /**
         * ApproveRequest
         * @description Which address this candidate is approved for (ADR-008).
         */
        ApproveRequest: {
            /** Reason */
            reason?: string | null;
            /**
             * Recipient Contact Point Id
             * Format: uuid
             */
            recipient_contact_point_id: string;
            /** Record Version */
            record_version?: string | null;
        };
        /**
         * ApproveResponse
         * @description What was approved, in the terms the approver chose it.
         */
        ApproveResponse: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Recipient */
            recipient: string;
            /**
             * Recipient Contact Point Id
             * Format: uuid
             */
            recipient_contact_point_id: string;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            state: components["schemas"]["CampaignCandidateState"];
        };
        /**
         * AttentionPage
         * @description Approvals needing attention, oldest first.
         */
        AttentionPage: {
            /** Items */
            items: components["schemas"]["AttentionRow"][];
        };
        /**
         * AttentionRow
         * @description One approval that no longer authorizes a send (§7.5, §8.4).
         */
        AttentionRow: {
            /**
             * Approval Expires At
             * Format: date-time
             */
            approval_expires_at: string;
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /** Approver Id */
            approver_id: string;
            /**
             * Message Revision Id
             * Format: uuid
             */
            message_revision_id: string;
            /** Reason */
            reason: string;
            /**
             * Recipient Contact Point Id
             * Format: uuid
             */
            recipient_contact_point_id: string;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            trigger: components["schemas"]["InvalidationTrigger"];
            /** Triggering Id */
            triggering_id: string | null;
        };
        /**
         * CampaignCandidateState
         * @description §8.2: imported -> eligible/ineligible -> research_pending -> researched ->
         *     review_pending -> approved/rejected/deferred/invalidated.
         * @enum {string}
         */
        CampaignCandidateState: "imported" | "eligible" | "ineligible" | "research_pending" | "researched" | "review_pending" | "approved" | "rejected" | "deferred" | "invalidated";
        /**
         * CandidateDetail
         * @description §12.3 items 1-5, and deliberately not 6 or 7.
         *
         *     Items 6 and 7 — the actions and the structured correction reason — are things a reviewer
         *     *does*, and this endpoint returns nothing that does anything. Approving, rejecting,
         *     deferring, editing, and requesting more research are `T-065` onwards; a read endpoint that
         *     shipped an action list would be describing authority it does not enforce.
         */
        CandidateDetail: {
            /** Account Domain */
            account_domain: string;
            /** Account Name */
            account_name: string;
            /** Approved Claims */
            approved_claims: components["schemas"]["ClaimRow"][];
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /** Campaign Name */
            campaign_name: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Contact Name */
            contact_name: string | null;
            /** Contact Points */
            contact_points: components["schemas"]["ContactPointRow"][];
            /** Contact Role */
            contact_role: string | null;
            /** Crm Relationship */
            crm_relationship?: null;
            current_revision: components["schemas"]["RevisionDetail"] | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRow"][];
            /** Opportunity Type */
            opportunity_type: string | null;
            /** Product Name */
            product_name: string;
            product_readiness: components["schemas"]["ReadinessCategory"] | null;
            /** Product Readiness Summary */
            product_readiness_summary: string | null;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            state: components["schemas"]["CampaignCandidateState"];
            suppression: components["schemas"]["SuppressionWarning"];
            /** What Happens Next */
            what_happens_next: string;
        };
        /**
         * CandidatePage
         * @description One page, and enough to ask for the next without guessing.
         */
        CandidatePage: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["CandidateRow"][];
            /** Total */
            total: number;
        };
        /**
         * CandidateRow
         * @description One queue entry: enough to choose what to open, not enough to decide.
         *
         *     §12.3's review card wants evidence, product status, claims, and the exact revision. None of
         *     that is here on purpose — a list endpoint that returned everything a decision needs would
         *     invite deciding from the list, and the card is `T-064`.
         */
        CandidateRow: {
            /** Account Domain */
            account_domain: string;
            /** Account Name */
            account_name: string;
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /** Campaign Name */
            campaign_name: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Contact Name */
            contact_name: string | null;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            state: components["schemas"]["CampaignCandidateState"];
        };
        /**
         * ClaimRow
         * @description One approved claim currently usable for this campaign (§10.5).
         */
        ClaimRow: {
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /** Claim Key */
            claim_key: string;
            /** Expires Or Review By */
            expires_or_review_by: string | null;
            /** Text */
            text: string;
            /** Version */
            version: number;
        };
        /**
         * ContactPointRow
         * @description One address a candidate could be approved for (§12.3 item 1, ADR-008).
         *
         *     The verification state is on the row rather than filtered on: an unverified address is shown
         *     and refused, not hidden. A reviewer who cannot see the mailbox they expected has no way to
         *     tell "this address is unusable" from "the system does not know about it", and those want
         *     different actions.
         */
        ContactPointRow: {
            /** Approvable */
            approvable: boolean;
            /**
             * Contact Point Id
             * Format: uuid
             */
            contact_point_id: string;
            type: components["schemas"]["ContactPointType"];
            /** Value */
            value: string;
            verification_state: components["schemas"]["VerificationState"];
        };
        /**
         * ContactPointType
         * @enum {string}
         */
        ContactPointType: "email" | "phone" | "linkedin_url";
        /**
         * DecisionCategory
         * @description §10.6's eleven categories, in the specification's order.
         *
         *     The order is kept so the list can be checked against §10.6 by reading down it. The values are
         *     stable identifiers: a dashboard may relabel them, but a stored row means what it meant.
         * @enum {string}
         */
        DecisionCategory: "wrong_campaign" | "wrong_account_or_duplicate" | "poor_buyer_role" | "weak_or_stale_evidence" | "product_not_ready" | "unsupported_claim" | "personalization_not_useful" | "tone_or_positioning_problem" | "existing_relationship" | "compliance_or_suppression_concern" | "defer_until_date_or_event";
        /**
         * DecisionResponse
         * @description What was recorded, so the dashboard can show it back rather than assume it.
         */
        DecisionResponse: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            category: components["schemas"]["DecisionCategory"];
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            /** Defer Until Date */
            defer_until_date: string | null;
            /** Defer Until Event */
            defer_until_event: string | null;
            /** Kind */
            kind: string;
            /** Notes */
            notes: string | null;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            state: components["schemas"]["CampaignCandidateState"];
        };
        /**
         * DeferRequest
         * @description What this candidate is waiting for (§10.6's eleventh category).
         */
        DeferRequest: {
            /** @default defer_until_date_or_event */
            category: components["schemas"]["DecisionCategory"];
            /** Notes */
            notes?: string | null;
            /** Record Version */
            record_version?: string | null;
            /** Until Date */
            until_date?: string | null;
            /** Until Event */
            until_event?: string | null;
        };
        /**
         * EditRequest
         * @description What a reviewer changed, and why.
         *
         *     ``correction_reason`` is required with no default: §12.3 item 7 asks for a structured reason,
         *     and an edit nobody can explain later is an edit nobody can review. Citations are optional and
         *     `None` means *unchanged* — silently dropping the claim a sentence rests on would fail
         *     `T-055`'s grounding check for a reason the reviewer never chose.
         */
        EditRequest: {
            /** Approved Claim Ids */
            approved_claim_ids?: string[] | null;
            /** Body */
            body: string;
            /** Correction Reason */
            correction_reason: string;
            /** Evidence Ids */
            evidence_ids?: string[] | null;
            /** Record Version */
            record_version?: string | null;
            /** Subject */
            subject: string;
        };
        /**
         * EditResponse
         * @description The new revision, and what the edit did to the old one.
         */
        EditResponse: {
            /** Expired Approvals */
            expired_approvals: string[];
            /** Failed Checks */
            failed_checks: string[];
            /** Is Valid */
            is_valid: boolean;
            revision: components["schemas"]["RevisionDetail"];
            /** Revoked Approvals */
            revoked_approvals: string[];
            /**
             * Superseded Revision Id
             * Format: uuid
             */
            superseded_revision_id: string;
        };
        /**
         * EvidenceRow
         * @description One stored fact, with the provenance §14.3 requires a reviewer to see.
         */
        EvidenceRow: {
            /** Contains Personal Or Confidential Data */
            contains_personal_or_confidential_data: boolean;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Excerpt */
            excerpt: string;
            /** Expires Or Refresh By */
            expires_or_refresh_by: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            source_quality: components["schemas"]["SourceQuality"];
            source_type: components["schemas"]["SourceType"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvalidationTrigger
         * @description Which §8.4 condition stopped an approval authorizing a send.
         *
         *     §8.4 lists six changes that invalidate an approval — recipient, subject, body, material
         *     personalization fact, product status, and claim version — plus the two lifecycle facts that
         *     also stop one being usable: the approval's own state, and its expiry. The three pinned values
         *     on the row cover all six of the §8.4 six, which is why there are fewer members here than that
         *     list has entries: the content hash covers recipient, subject, body, and personalization
         *     together, because any of them changing changes the hash.
         * @enum {string}
         */
        InvalidationTrigger: "not_approved" | "expired" | "revision_missing" | "revision_retired" | "content_changed" | "recipient_changed" | "product_status_superseded" | "claim_set_superseded";
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * MessageRevisionState
         * @description §8.2: draft -> validation_failed/review_pending -> approved/superseded/invalidated.
         * @enum {string}
         */
        MessageRevisionState: "draft" | "validation_failed" | "review_pending" | "approved" | "superseded" | "invalidated";
        /** Readiness */
        Readiness: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /** Detail */
            detail?: string | null;
            /** Shadow Mode */
            shadow_mode: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * ReadinessCategory
         * @description The five states §2.3 requires the system to distinguish.
         *
         *     A database enum, not free text: "roughly available" is exactly the ambiguity that produces a
         *     premature certification or availability claim.
         * @enum {string}
         */
        ReadinessCategory: "sellable_now" | "evaluation_or_pilot" | "in_development" | "strategic_or_roadmap" | "paused_or_unavailable";
        /**
         * RejectRequest
         * @description Why this candidate is being rejected (§10.6).
         */
        RejectRequest: {
            category: components["schemas"]["DecisionCategory"];
            /** Notes */
            notes?: string | null;
            /** Record Version */
            record_version?: string | null;
        };
        /**
         * RequestResearchRequest
         * @description Why more evidence is wanted (§10.6, ADR-022).
         */
        RequestResearchRequest: {
            category: components["schemas"]["DecisionCategory"];
            /** Notes */
            notes?: string | null;
            /** Record Version */
            record_version?: string | null;
        };
        /**
         * RevisionDetail
         * @description The exact revision a reviewer would act on (§12.3 item 5).
         *
         *     The full body, unlike the queue row — this *is* the place a reviewer reads the message, and
         *     approving without seeing exactly what will be sent is the failure ADR-008 exists to prevent.
         */
        RevisionDetail: {
            /** Approved Claim Ids */
            approved_claim_ids: string[];
            /** Body */
            body: string;
            /** Content Hash */
            content_hash: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
            state: components["schemas"]["MessageRevisionState"];
            /** Subject */
            subject: string;
        };
        /**
         * RevisionPage
         * @description One page of the revision queue.
         */
        RevisionPage: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["RevisionRow"][];
            /** Total */
            total: number;
        };
        /**
         * RevisionRow
         * @description One revision waiting on a reviewer.
         *
         *     Carries the subject but **not** the body: a queue is for choosing what to open, and a list
         *     that showed the whole message would invite approving from the list. The body, its evidence,
         *     and its claims are the review card's (`T-064`).
         */
        RevisionRow: {
            /** Backlog Age Hours */
            backlog_age_hours: number;
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /** Campaign Name */
            campaign_name: string;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Opportunity Type */
            opportunity_type: string | null;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
            state: components["schemas"]["MessageRevisionState"];
            /** Subject */
            subject: string;
        };
        /**
         * RevokeApprovalRequest
         * @description Why this approval is being revoked.
         */
        RevokeApprovalRequest: {
            /** Reason */
            reason: string;
            /** Record Version */
            record_version?: string | null;
        };
        /**
         * RevokeApprovalResponse
         * @description What the revocation did.
         */
        RevokeApprovalResponse: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /** Reason */
            reason: string;
            /**
             * Record Version
             * Format: date-time
             */
            record_version: string;
            /** State */
            state: string;
        };
        /**
         * SessionResponse
         * @description The current session. `token` is present only on the response that created it.
         */
        SessionResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Issued Via */
            issued_via: string;
            /** Roles */
            roles: string[];
            /** Token */
            token?: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * SourceQuality
         * @description §9.5 / §10.4 source-quality classification.
         * @enum {string}
         */
        SourceQuality: "high" | "medium" | "low";
        /**
         * SourceType
         * @description Where evidence came from (§9.2).
         *
         *     ``LINKEDIN_HUMAN_PROVIDED`` is the only LinkedIn value and says what it means: a human
         *     supplied the URL or export. Autonomous LinkedIn operation is rejected (ADR-005).
         * @enum {string}
         */
        SourceType: "company_website" | "industry_directory" | "trade_show_listing" | "public_announcement" | "procurement_record" | "data_provider" | "crm_record" | "linkedin_human_provided" | "manual_entry" | "synthetic_fixture";
        /**
         * StubSignInRequest
         * @description Who to sign in. There is no password field, and that is `§12.2` rather than an omission.
         */
        StubSignInRequest: {
            /** Email */
            email: string;
        };
        /**
         * SuppressionWarning
         * @description §12.3 item 4. Two scopes, reported separately because they mean different things.
         */
        SuppressionWarning: {
            /** Account Suppressed */
            account_suppressed: boolean;
            /** Contact Suppressed */
            contact_suppressed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationState
         * @description Whether an address has been confirmed reachable (§15.8).
         *
         *     ``UNVERIFIED`` is the default and is *not* a soft yes: campaign policy defaults to requiring
         *     verification before a send is considered (`T-015`).
         * @enum {string}
         */
        VerificationState: "unverified" | "verified" | "invalid";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_api_auth_session_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stub_sign_in_endpoint_api_auth_stub_sign_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StubSignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_approval_endpoint_api_review_approvals__approval_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                approval_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approvals_needing_attention_endpoint_api_review_attention_approvals_get: {
        parameters: {
            query?: {
                campaign_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_review_candidates_get: {
        parameters: {
            query?: {
                campaign_id?: string | null;
                state?: components["schemas"]["CampaignCandidateState"] | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_review_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_candidate_endpoint_api_review_candidates__candidate_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defer_candidate_endpoint_api_review_candidates__candidate_id__defer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_candidate_endpoint_api_review_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_more_research_endpoint_api_review_candidates__candidate_id__request_research_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_review_revisions_get: {
        parameters: {
            query?: {
                campaign_id?: string | null;
                state?: components["schemas"]["MessageRevisionState"] | null;
                opportunity_type?: string | null;
                min_age_hours?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_message_endpoint_api_review_revisions__revision_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                revision_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_revision_endpoint_api_review_revisions__revision_id__edit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                revision_id: string;
            };
            cookie?: {
                mp_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
